export type NotificationChannel = "telegram_admin" | "telegram_worker";
export type NotificationCategory = "requests" | "orders" | "workers" | "execution" | "system";
export type NotificationRecipientType = "admin" | "manager" | "worker" | "system";

export interface NotificationVariableDefinition {
  key: string;
  label: string;
  description: string;
  exampleValue: string;
  group: string;
  sortOrder: number;
}

export interface NotificationTemplateDefinition {
  key: string;
  name: string;
  channel: NotificationChannel;
  category: NotificationCategory;
  recipientType: NotificationRecipientType;
  defaultTemplate: string;
  supportsHtml: boolean;
  hasInteractiveButtons: boolean;
  variables: NotificationVariableDefinition[];
  serviceTemplates?: NotificationServiceTemplateDefinition[];
}

export interface NotificationServiceTemplateDefinition {
  serviceSlug: string;
  name?: string;
  bodyTemplate: string;
  notes?: string;
}

const commonRequestVariables: NotificationVariableDefinition[] = [
  variable("request.id", "ID заявки", "Внутрішній ID заявки", "REQ-1024", "Request", 10),
  variable("request.customerName", "Клієнт", "Ім'я клієнта", "Іван Петренко", "Request", 20),
  variable("request.phone", "Телефон", "Номер телефону клієнта", "+380991112233", "Request", 30),
  variable("request.email", "Email", "Email клієнта, якщо вказаний", "client@example.com", "Request", 40),
  variable("request.addressFrom", "Адреса", "Основна адреса заявки", "Львів, вул. Городоцька, 120", "Request", 50),
  variable("request.addressTo", "Адреса доставки", "Кінцева адреса, якщо є", "Львів, вул. Шевченка, 30", "Request", 60),
  variable("request.comment", "Коментар", "Коментар клієнта", "Потрібно якнайшвидше", "Request", 70),
  variable("request.createdAt", "Створено", "Дата і час створення заявки", "24.04.2026, 10:30", "Request", 80),
  variable("request.date", "Дата", "Дата виконання, якщо вказана", "25.04.2026", "Request", 90),
  variable("request.time", "Час", "Час виконання, якщо вказаний", "10:00", "Request", 100),
  variable("request.period", "Період", "Період оренди або виконання", "25.04.2026 — 26.04.2026", "Request", 110),
  variable("request.currentPosition", "Поточна позиція", "Поточна позиція техніки або евакуатора", "Львів, вул. Зелена, 10", "Request", 120),
  variable("request.pickupMapLink", "Посилання на точку A", "HTML-посилання Google Maps на першу точку", "<a href=\"...\">📍 Точка A</a>", "Request", 130),
  variable("request.destinationMapLink", "Посилання на точку B", "HTML-посилання Google Maps на другу точку", "<a href=\"...\">🏁 Точка B</a>", "Request", 140),
  variable("request.truckDispatchDistance", "Подача", "Відстань подачі евакуатора", "6.4 км", "Tow", 150),
  variable("request.truckDispatchEta", "Час подачі", "Орієнтовний час подачі евакуатора", "18 хв", "Tow", 160),
  variable("request.clientRouteDistance", "Маршрут клієнта", "Відстань евакуації між точками", "12.1 км", "Tow", 170),
  variable("request.clientRouteEta", "Час евакуації", "Орієнтовний час евакуації", "32 хв", "Tow", 180),
  variable("request.totalRouteDistance", "Загальний маршрут", "Подача плюс маршрут клієнта", "18.5 км", "Tow", 190),
  variable("request.estimatedCost", "Орієнтовна вартість", "Орієнтовна вартість заявки", "2 400 грн", "Tow", 200),
  variable("material.name", "Матеріал", "Назва матеріалу", "Пісок", "Material", 210),
  variable("material.quantity", "Кількість", "Кількість матеріалу", "5", "Material", 220),
  variable("material.unit", "Одиниця", "Одиниця виміру матеріалу", "т", "Material", 230),
  variable("material.deliveryAddress", "Адреса доставки", "Адреса доставки матеріалу", "Львів, вул. Шевченка, 30", "Material", 240),
  variable("material.supplierPointName", "Точка постачання", "Назва точки постачання", "Кар'єр Сокільники", "Material", 250),
  variable("material.supplierPointAddress", "Адреса точки", "Адреса точки постачання", "Сокільники, Львівська область", "Material", 260),
  variable("material.materialCost", "Вартість матеріалу", "Орієнтовна вартість матеріалу", "1 800 грн", "Material", 270),
  variable("material.deliveryCost", "Вартість доставки", "Орієнтовна вартість доставки", "900 грн", "Material", 280),
  variable("material.totalCost", "Разом", "Орієнтовна загальна вартість", "2 700 грн", "Material", 290),
  variable("material.truckToPointKm", "Техніка до точки", "Відстань від техніки до точки постачання", "4.2 км", "Material", 300),
  variable("material.pointToClientKm", "Точка до клієнта", "Відстань від точки постачання до клієнта", "11.8 км", "Material", 310),
  variable("service.title", "Послуга", "Назва послуги", "Послуги евакуатора", "Service", 320),
  variable("service.slug", "Slug послуги", "Технічний slug послуги для service-specific шаблонів", "poslugy-evakuatora", "Service", 330),
  variable("system.siteUrl", "Сайт", "Публічний URL сайту", "https://technorent.ua", "System", 340),
];

const commonOrderVariables: NotificationVariableDefinition[] = [
  variable("order.id", "ID замовлення", "Внутрішній ID замовлення", "ORD-2048", "Order", 10),
  variable("order.status", "Статус", "Поточний статус замовлення", "CONFIRMED", "Order", 20),
  variable("order.customerName", "Клієнт", "Ім'я клієнта", "Олег Коваль", "Order", 30),
  variable("order.customerPhone", "Телефон клієнта", "Номер телефону клієнта", "+380671234567", "Order", 40),
  variable("order.plannedStart", "Коли почати", "Планова дата і час початку", "25.04.2026, 10:00", "Order", 50),
  variable("order.executionTime", "Час виконання", "Плановий час або інтервал виконання", "25.04.2026, 10:00-13:00", "Order", 60),
  variable("order.itemsText", "Техніка / послуги", "Підготовлений список позицій замовлення", "MAN TGS 33.400", "Order", 70),
  variable("order.locationsText", "Точки", "Підготовлений список адрес або точок", "Звідки: Сокільники\nКуди: Львів", "Order", 80),
  variable("order.detailsText", "Деталі", "Підготовлений список додаткових деталей", "Матеріал: Пісок\nКількість: 5 т", "Order", 90),
  variable("order.managerComment", "Коментар менеджера", "Коментар менеджера для працівника", "Зателефонувати за 30 хв", "Order", 100),
  variable("order.workerCompensationText", "Оплата працівника", "Підготовлений текст із сумою або формулою оплати працівника", "Фіксовано: 1500 грн", "Order", 110),
  variable("order.finalPrice", "Фінальна сума", "Фінально погоджена сума", "4 155 грн", "Order", 120),
  variable("service.title", "Послуга", "Назва послуги або тип замовлення", "Послуги евакуатора", "Service", 130),
  variable("service.slug", "Slug послуги", "Технічний slug послуги для service-specific шаблонів", "poslugy-evakuatora", "Service", 140),
];

const workerVariables: NotificationVariableDefinition[] = [
  variable("worker.name", "Працівник", "Ім'я працівника", "Микола Гусір", "Worker", 10),
  variable("worker.phone", "Телефон працівника", "Телефон працівника", "+380501112233", "Worker", 20),
  variable("worker.responseComment", "Коментар відповіді", "Коментар при прийнятті або відхиленні", "Прийняв", "Worker", 30),
];

const executionVariables: NotificationVariableDefinition[] = [
  variable("execution.startedAt", "Початок", "Фактичний час початку", "24.04.2026, 11:10", "Execution", 10),
  variable("execution.finishedAt", "Завершення", "Фактичний час завершення", "24.04.2026, 13:40", "Execution", 20),
  variable("report.cashAmount", "Готівка", "Сума готівки з анкети", "0 грн", "Report", 30),
  variable("report.extraExpenses", "Додаткові витрати", "Додаткові витрати з анкети", "0 грн", "Report", 40),
  variable("report.workerComment", "Коментар працівника", "Коментар після завершення", "Виконано без проблем", "Report", 50),
  variable("gps.lastAddress", "GPS адреса", "Остання адреса GPS-маячка", "Львів, вул. Зелена, 10", "GPS", 60),
];

export const notificationTemplateRegistry: NotificationTemplateDefinition[] = [
  {
    key: "new_site_request_admin",
    name: "Нова заявка з сайту адміну",
    channel: "telegram_admin",
    category: "requests",
    recipientType: "admin",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: commonRequestVariables,
    defaultTemplate: [
      "📋 <b>Нова заявка з сайту</b>",
      "━━━━━━━━━━━━━━━━━━",
      "👤 <b>Клієнт:</b> {{request.customerName}}",
      "📞 <b>Телефон:</b> {{request.phone}}",
      "📧 <b>Email:</b> {{request.email}}",
      "🛠️ <b>Позиція:</b> {{service.title}}",
      "📅 <b>Період:</b> {{request.period}}",
      "📍 <b>Адреса:</b> {{request.addressFrom}}",
      "",
      "💬 <b>Коментар:</b>",
      "✎ {{request.comment}}",
      "",
      "⏰ <b>Створено:</b> {{request.createdAt}}",
    ].join("\n"),
  },
  {
    key: "new_service_request_admin",
    name: "Нова заявка на послугу адміну",
    channel: "telegram_admin",
    category: "requests",
    recipientType: "admin",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: commonRequestVariables,
    defaultTemplate: [
      "🚛 <b>Нова заявка: {{service.title}}</b>",
      "━━━━━━━━━━━━━━━━━━",
      "",
      "👤 <b>Ім'я:</b> {{request.customerName}}",
      "📞 <b>Телефон:</b> {{request.phone}}",
      "📍 <b>Адреса:</b> {{request.addressFrom}}",
      "📅 <b>Дата:</b> {{request.date}}",
      "🕐 <b>Час:</b> {{request.time}}",
      "",
      "💬 <b>Коментар:</b> {{request.comment}}",
      "",
      "⏰ <b>Створено:</b> {{request.createdAt}}",
    ].join("\n"),
    serviceTemplates: [
      {
        serviceSlug: "poslugy-evakuatora",
        name: "Нова заявка на евакуатор адміну",
        notes: "Дефолтний service-specific шаблон для заявки евакуатора.",
        bodyTemplate: [
          "🚨 <b>НОВА ЗАЯВКА: {{service.title}}</b> 🚨",
          "━━━━━━━━━━━━━━━━━━",
          "👤 <b>Клієнт:</b> {{request.customerName}}",
          "📞 <b>Телефон:</b> {{request.phone}}",
          "",
          "🗺️ <b>МАРШРУТ</b>",
          "┣ 📍 <b>Звідки:</b> {{request.addressFrom}}",
          "┗ 🏁 <b>Куди:</b> {{request.addressTo}}",
          "🔗 {{request.pickupMapLink}} • {{request.destinationMapLink}}",
          "",
          "📊 <b>РОЗРАХУНОК</b>",
          "┣ 🚚 <b>Подача евакуатора:</b> {{request.truckDispatchDistance}}",
          "┣ ⏱ <b>Час подачі:</b> {{request.truckDispatchEta}}",
          "┣ 🛣 <b>Маршрут клієнта:</b> {{request.clientRouteDistance}}",
          "┣ ⌛ <b>Час евакуації:</b> {{request.clientRouteEta}}",
          "┣ 📏 <b>Загальний маршрут:</b> {{request.totalRouteDistance}}",
          "┗ 💰 <b>Орієнтовна вартість:</b> {{request.estimatedCost}}",
          "",
          "💬 <b>КОМЕНТАР</b>",
          "✎ {{request.comment}}",
          "",
          "⏰ <b>Створено:</b> {{request.createdAt}}",
        ].join("\n"),
      },
      {
        serviceSlug: "perevezennia-sypuchyh-materialiv",
        name: "Нова заявка на перевезення матеріалів адміну",
        notes: "Дефолтний service-specific шаблон для калькулятора доставки матеріалів.",
        bodyTemplate: [
          "🚛 <b>НОВА ЗАЯВКА: {{service.title}}</b>",
          "━━━━━━━━━━━━━━━━━━",
          "👤 <b>Клієнт:</b> {{request.customerName}}",
          "📞 <b>Телефон:</b> {{request.phone}}",
          "",
          "📦 <b>МАТЕРІАЛ</b>",
          "┣ <b>Назва:</b> {{material.name}}",
          "┣ <b>Кількість:</b> {{material.quantity}} {{material.unit}}",
          "┗ <b>Разом:</b> {{material.totalCost}}",
          "",
          "🗺️ <b>ЛОГІСТИКА</b>",
          "┣ 📍 <b>Точка постачання:</b> {{material.supplierPointName}}",
          "┣ 🏭 <b>Адреса точки:</b> {{material.supplierPointAddress}}",
          "┗ 🏁 <b>Доставка клієнту:</b> {{material.deliveryAddress}}",
          "",
          "📊 <b>РОЗРАХУНОК</b>",
          "┣ Матеріал: {{material.materialCost}}",
          "┣ Доставка: {{material.deliveryCost}}",
          "┣ Техніка → точка: {{material.truckToPointKm}}",
          "┗ Точка → клієнт: {{material.pointToClientKm}}",
          "",
          "💬 <b>Коментар:</b> {{request.comment}}",
          "⏰ <b>Створено:</b> {{request.createdAt}}",
        ].join("\n"),
      },
      {
        serviceSlug: "vyviz-budivelnogo-smittia",
        name: "Нова заявка на вивіз сміття адміну",
        notes: "Дефолтний service-specific шаблон для заявки на вивіз будівельного сміття.",
        bodyTemplate: [
          "🚛 <b>Нова заявка: {{service.title}}</b>",
          "━━━━━━━━━━━━━━━━━━",
          "👤 <b>Ім'я:</b> {{request.customerName}}",
          "📞 <b>Телефон:</b> {{request.phone}}",
          "📍 <b>Адреса:</b> {{request.addressFrom}}",
          "📅 <b>Дата:</b> {{request.date}}",
          "🕐 <b>Час:</b> {{request.time}}",
          "",
          "💬 <b>Коментар:</b>",
          "{{request.comment}}",
          "",
          "⏰ <b>Створено:</b> {{request.createdAt}}",
        ].join("\n"),
      },
    ],
  },
  {
    key: "worker_assignment_sent",
    name: "Працівнику надіслано нове завдання",
    channel: "telegram_worker",
    category: "workers",
    recipientType: "worker",
    supportsHtml: true,
    hasInteractiveButtons: true,
    variables: [...commonOrderVariables, ...workerVariables],
    defaultTemplate: [
      "📌 <b>Нове завдання</b>",
      "№ замовлення: <code>{{order.id}}</code>",
      "👤 Клієнт: <b>{{order.customerName}}</b>",
      "☎️ Телефон: {{order.customerPhone}}",
      "⏰ Почати: <b>{{order.plannedStart}}</b>",
      "",
      "📍 <b>Точки:</b>",
      "{{order.locationsText}}",
      "",
      "🚜 <b>Послідовність робіт:</b>",
      "{{order.itemsText}}",
      "",
      "ℹ️ <b>Деталі:</b>",
      "{{order.detailsText}}",
      "",
      "💰 <b>Ваша оплата:</b> {{order.workerCompensationText}}",
      "",
      "💬 Коментар: {{order.managerComment}}",
    ].join("\n"),
    serviceTemplates: [
      {
        serviceSlug: "poslugy-evakuatora",
        name: "Завдання працівнику: евакуатор",
        notes: "Працівнику показуються дві точки маршруту, деталі розрахунку і коментар менеджера.",
        bodyTemplate: [
          "📌 <b>Нове завдання: евакуатор</b>",
          "№ замовлення: <code>{{order.id}}</code>",
          "👤 Клієнт: <b>{{order.customerName}}</b>",
          "☎️ Телефон: {{order.customerPhone}}",
          "⏰ Почати: <b>{{order.plannedStart}}</b>",
          "",
          "📍 <b>Точки:</b>",
          "{{order.locationsText}}",
          "",
          "🚜 <b>Евакуатор / техніка:</b>",
          "{{order.itemsText}}",
          "",
          "ℹ️ <b>Деталі:</b>",
          "{{order.detailsText}}",
          "",
          "💰 <b>Ваша оплата:</b> {{order.workerCompensationText}}",
          "",
          "💬 Коментар менеджера: {{order.managerComment}}",
        ].join("\n"),
      },
      {
        serviceSlug: "perevezennia-sypuchyh-materialiv",
        name: "Завдання працівнику: перевезення матеріалів",
        notes: "Працівнику показуються точки завантаження/доставки і матеріальні деталі.",
        bodyTemplate: [
          "📌 <b>Нове завдання: доставка матеріалів</b>",
          "№ замовлення: <code>{{order.id}}</code>",
          "👤 Клієнт: <b>{{order.customerName}}</b>",
          "☎️ Телефон: {{order.customerPhone}}",
          "⏰ Почати: <b>{{order.plannedStart}}</b>",
          "",
          "📍 <b>Маршрут:</b>",
          "{{order.locationsText}}",
          "",
          "🚜 <b>Техніка:</b>",
          "{{order.itemsText}}",
          "",
          "📦 <b>Матеріал / розрахунок:</b>",
          "{{order.detailsText}}",
          "",
          "💰 <b>Ваша оплата:</b> {{order.workerCompensationText}}",
          "",
          "💬 Коментар менеджера: {{order.managerComment}}",
        ].join("\n"),
      },
    ],
  },
  {
    key: "worker_assignment_accepted_manager",
    name: "Працівник прийняв завдання менеджеру",
    channel: "telegram_admin",
    category: "workers",
    recipientType: "manager",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: [...commonOrderVariables, ...workerVariables],
    defaultTemplate: [
      "✅ <b>Працівник прийняв завдання</b>",
      "",
      "🧾 <b>Замовлення:</b> {{order.id}}",
      "👷 <b>Працівник:</b> {{worker.name}}",
      "👤 <b>Клієнт:</b> {{order.customerName}}",
      "📞 <b>Телефон:</b> {{order.customerPhone}}",
    ].join("\n"),
  },
  {
    key: "worker_assignment_declined_manager",
    name: "Працівник відхилив завдання менеджеру",
    channel: "telegram_admin",
    category: "workers",
    recipientType: "manager",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: [...commonOrderVariables, ...workerVariables],
    defaultTemplate: [
      "❌ <b>Працівник відхилив завдання</b>",
      "",
      "🧾 <b>Замовлення:</b> {{order.id}}",
      "👷 <b>Працівник:</b> {{worker.name}}",
      "👤 <b>Клієнт:</b> {{order.customerName}}",
      "📞 <b>Телефон:</b> {{order.customerPhone}}",
      "💬 <b>Коментар:</b> {{worker.responseComment}}",
    ].join("\n"),
  },
  {
    key: "execution_started_manager",
    name: "Працівник розпочав виконання менеджеру",
    channel: "telegram_admin",
    category: "execution",
    recipientType: "manager",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: [...commonOrderVariables, ...workerVariables, ...executionVariables],
    defaultTemplate: [
      "🚀 <b>Працівник розпочав виконання</b>",
      "",
      "🧾 <b>Замовлення:</b> {{order.id}}",
      "👷 <b>Працівник:</b> {{worker.name}}",
      "👤 <b>Клієнт:</b> {{order.customerName}}",
      "📞 <b>Телефон:</b> {{order.customerPhone}}",
    ].join("\n"),
  },
  {
    key: "execution_finished_manager",
    name: "Працівник завершив виконання менеджеру",
    channel: "telegram_admin",
    category: "execution",
    recipientType: "manager",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: [...commonOrderVariables, ...workerVariables, ...executionVariables],
    defaultTemplate: [
      "🏁 <b>Працівник завершив виконання</b>",
      "",
      "🧾 <b>Замовлення:</b> {{order.id}}",
      "👷 <b>Працівник:</b> {{worker.name}}",
      "👤 <b>Клієнт:</b> {{order.customerName}}",
      "📞 <b>Телефон:</b> {{order.customerPhone}}",
    ].join("\n"),
  },
  {
    key: "worker_report_submitted_manager",
    name: "Працівник завершив анкету менеджеру",
    channel: "telegram_admin",
    category: "execution",
    recipientType: "manager",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: [...commonOrderVariables, ...workerVariables, ...executionVariables],
    defaultTemplate: [
      "🧾 <b>Працівник заповнив підсумковий звіт</b>",
      "",
      "🧾 <b>Замовлення:</b> {{order.id}}",
      "👷 <b>Працівник:</b> {{worker.name}}",
      "👤 <b>Клієнт:</b> {{order.customerName}}",
      "📞 <b>Телефон:</b> {{order.customerPhone}}",
      "💬 <b>Коментар:</b> {{report.workerComment}}",
    ].join("\n"),
  },
  {
    key: "order_closed_manager",
    name: "Замовлення фінально закрито менеджером",
    channel: "telegram_admin",
    category: "orders",
    recipientType: "manager",
    supportsHtml: true,
    hasInteractiveButtons: false,
    variables: [...commonOrderVariables, ...workerVariables, ...executionVariables],
    defaultTemplate: [
      "✅ <b>Замовлення фінально закрито</b>",
      "",
      "🧾 <b>Замовлення:</b> {{order.id}}",
      "👤 <b>Клієнт:</b> {{order.customerName}}",
      "📞 <b>Телефон:</b> {{order.customerPhone}}",
      "💰 <b>Фінальна сума:</b> {{order.finalPrice}}",
    ].join("\n"),
  },
];

export function getNotificationTemplateDefinition(key: string) {
  return notificationTemplateRegistry.find((template) => template.key === key) ?? null;
}

function variable(
  key: string,
  label: string,
  description: string,
  exampleValue: string,
  group: string,
  sortOrder: number,
): NotificationVariableDefinition {
  return { key, label, description, exampleValue, group, sortOrder };
}
